version: "3.9"

services:
  grpc-server:
    build:
      context: .
      args:
        - APP_BASE=server
    container_name: grpc-server
    command: bash -c "rm -f /tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - ./server:/srv/app
    ports:
      - "8001:3000"
      - "50051:50051"
    networks:
      - grpc-ruby

  grpc-client:
    build:
      context: .
      args:
        - APP_BASE=client
    container_name: grpc-client
    command: bash -c "rm -f /tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./client:/srv/app
    ports:
      - "8002:3000"
    networks:
      - grpc-ruby

networks:
  grpc-ruby:
    external: true
